annotations:
  catalog.cattle.io/display-name: Node Config Operator
  catalog.cattle.io/namespace: nco-system
  catalog.cattle.io/release-name: nco
apiVersion: v2
appVersion: v0.2.0
description: Operator to configure Kubernetes' nodes
name: node-config-operator
type: application
version: 0.2.0
