apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-configuration-whitesdnconfig-viewer-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - configuration.whitestack.com
  resources:
  - whitesdnconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configuration.whitestack.com
  resources:
  - whitesdnconfigs/status
  verbs:
  - get
