apiVersion: v1
annotations:
  catalog.cattle.io/display-name: Jaeger Operator
  catalog.cattle.io/release-name: jaeger-operator
  catalog.cattle.io/kube-version: '>= 1.19.0-0 < 1.30.0-0'
  catalog.cattle.io/namespace: jaeger-operator
appVersion: 1.61.0
description: jaeger-operator Helm chart for Kubernetes
home: https://www.jaegertracing.io/
icon: https://www.jaegertracing.io/img/jaeger-icon-reverse-color.svg
maintainers:
- email: ctadeu@gmail.com
  name: cpanato
- email: batazor111@gmail.com
  name: batazor
name: jaeger-operator
sources:
- https://github.com/jaegertracing/jaeger-operator
version: 2.57.0
